var wms_layers = [];


        var lyr_OpenStreetMap_0 = new ol.layer.Tile({
            'title': 'OpenStreetMap',
            'type': 'base',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
    attributions: ' ',
                url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
            })
        });
var format_Bendosari_Sawit_1 = new ol.format.GeoJSON();
var features_Bendosari_Sawit_1 = format_Bendosari_Sawit_1.readFeatures(json_Bendosari_Sawit_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Bendosari_Sawit_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Bendosari_Sawit_1.addFeatures(features_Bendosari_Sawit_1);
var lyr_Bendosari_Sawit_1 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Bendosari_Sawit_1, 
                style: style_Bendosari_Sawit_1,
                interactive: true,
                title: '<img src="styles/legend/Bendosari_Sawit_1.png" /> Bendosari_Sawit'
            });
var format_Cepokosawit_Sawit_2 = new ol.format.GeoJSON();
var features_Cepokosawit_Sawit_2 = format_Cepokosawit_Sawit_2.readFeatures(json_Cepokosawit_Sawit_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Cepokosawit_Sawit_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Cepokosawit_Sawit_2.addFeatures(features_Cepokosawit_Sawit_2);
var lyr_Cepokosawit_Sawit_2 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Cepokosawit_Sawit_2, 
                style: style_Cepokosawit_Sawit_2,
                interactive: true,
                title: '<img src="styles/legend/Cepokosawit_Sawit_2.png" /> Cepokosawit_Sawit'
            });
var format_Gombang_Sawit_3 = new ol.format.GeoJSON();
var features_Gombang_Sawit_3 = format_Gombang_Sawit_3.readFeatures(json_Gombang_Sawit_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Gombang_Sawit_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Gombang_Sawit_3.addFeatures(features_Gombang_Sawit_3);
var lyr_Gombang_Sawit_3 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Gombang_Sawit_3, 
                style: style_Gombang_Sawit_3,
                interactive: true,
                title: '<img src="styles/legend/Gombang_Sawit_3.png" /> Gombang_Sawit'
            });
var format_Guwokajen_Sawit_4 = new ol.format.GeoJSON();
var features_Guwokajen_Sawit_4 = format_Guwokajen_Sawit_4.readFeatures(json_Guwokajen_Sawit_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Guwokajen_Sawit_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Guwokajen_Sawit_4.addFeatures(features_Guwokajen_Sawit_4);
var lyr_Guwokajen_Sawit_4 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Guwokajen_Sawit_4, 
                style: style_Guwokajen_Sawit_4,
                interactive: true,
                title: '<img src="styles/legend/Guwokajen_Sawit_4.png" /> Guwokajen_Sawit'
            });
var format_Jatirejo_Sawit_5 = new ol.format.GeoJSON();
var features_Jatirejo_Sawit_5 = format_Jatirejo_Sawit_5.readFeatures(json_Jatirejo_Sawit_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Jatirejo_Sawit_5 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Jatirejo_Sawit_5.addFeatures(features_Jatirejo_Sawit_5);
var lyr_Jatirejo_Sawit_5 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Jatirejo_Sawit_5, 
                style: style_Jatirejo_Sawit_5,
                interactive: true,
                title: '<img src="styles/legend/Jatirejo_Sawit_5.png" /> Jatirejo_Sawit'
            });
var format_Jenengan_Sawit_6 = new ol.format.GeoJSON();
var features_Jenengan_Sawit_6 = format_Jenengan_Sawit_6.readFeatures(json_Jenengan_Sawit_6, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Jenengan_Sawit_6 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Jenengan_Sawit_6.addFeatures(features_Jenengan_Sawit_6);
var lyr_Jenengan_Sawit_6 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Jenengan_Sawit_6, 
                style: style_Jenengan_Sawit_6,
                interactive: true,
                title: '<img src="styles/legend/Jenengan_Sawit_6.png" /> Jenengan_Sawit'
            });
var format_Karangduren_Sawit_7 = new ol.format.GeoJSON();
var features_Karangduren_Sawit_7 = format_Karangduren_Sawit_7.readFeatures(json_Karangduren_Sawit_7, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Karangduren_Sawit_7 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Karangduren_Sawit_7.addFeatures(features_Karangduren_Sawit_7);
var lyr_Karangduren_Sawit_7 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Karangduren_Sawit_7, 
                style: style_Karangduren_Sawit_7,
                interactive: true,
                title: '<img src="styles/legend/Karangduren_Sawit_7.png" /> Karangduren_Sawit'
            });
var format_Kateguhan_Sawit_8 = new ol.format.GeoJSON();
var features_Kateguhan_Sawit_8 = format_Kateguhan_Sawit_8.readFeatures(json_Kateguhan_Sawit_8, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Kateguhan_Sawit_8 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Kateguhan_Sawit_8.addFeatures(features_Kateguhan_Sawit_8);
var lyr_Kateguhan_Sawit_8 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Kateguhan_Sawit_8, 
                style: style_Kateguhan_Sawit_8,
                interactive: true,
                title: '<img src="styles/legend/Kateguhan_Sawit_8.png" /> Kateguhan_Sawit'
            });
var format_Kemasan_Sawit_9 = new ol.format.GeoJSON();
var features_Kemasan_Sawit_9 = format_Kemasan_Sawit_9.readFeatures(json_Kemasan_Sawit_9, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Kemasan_Sawit_9 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Kemasan_Sawit_9.addFeatures(features_Kemasan_Sawit_9);
var lyr_Kemasan_Sawit_9 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Kemasan_Sawit_9, 
                style: style_Kemasan_Sawit_9,
                interactive: true,
                title: '<img src="styles/legend/Kemasan_Sawit_9.png" /> Kemasan_Sawit'
            });
var format_Manjung_Sawit_10 = new ol.format.GeoJSON();
var features_Manjung_Sawit_10 = format_Manjung_Sawit_10.readFeatures(json_Manjung_Sawit_10, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Manjung_Sawit_10 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Manjung_Sawit_10.addFeatures(features_Manjung_Sawit_10);
var lyr_Manjung_Sawit_10 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Manjung_Sawit_10, 
                style: style_Manjung_Sawit_10,
                interactive: true,
                title: '<img src="styles/legend/Manjung_Sawit_10.png" /> Manjung_Sawit'
            });
var format_Tegalrejo_Sawit_11 = new ol.format.GeoJSON();
var features_Tegalrejo_Sawit_11 = format_Tegalrejo_Sawit_11.readFeatures(json_Tegalrejo_Sawit_11, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Tegalrejo_Sawit_11 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Tegalrejo_Sawit_11.addFeatures(features_Tegalrejo_Sawit_11);
var lyr_Tegalrejo_Sawit_11 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Tegalrejo_Sawit_11, 
                style: style_Tegalrejo_Sawit_11,
                interactive: true,
                title: '<img src="styles/legend/Tegalrejo_Sawit_11.png" /> Tegalrejo_Sawit'
            });
var format_Tlawong_Sawit_12 = new ol.format.GeoJSON();
var features_Tlawong_Sawit_12 = format_Tlawong_Sawit_12.readFeatures(json_Tlawong_Sawit_12, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Tlawong_Sawit_12 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Tlawong_Sawit_12.addFeatures(features_Tlawong_Sawit_12);
var lyr_Tlawong_Sawit_12 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Tlawong_Sawit_12, 
                style: style_Tlawong_Sawit_12,
                interactive: true,
                title: '<img src="styles/legend/Tlawong_Sawit_12.png" /> Tlawong_Sawit'
            });

lyr_OpenStreetMap_0.setVisible(true);lyr_Bendosari_Sawit_1.setVisible(true);lyr_Cepokosawit_Sawit_2.setVisible(true);lyr_Gombang_Sawit_3.setVisible(true);lyr_Guwokajen_Sawit_4.setVisible(true);lyr_Jatirejo_Sawit_5.setVisible(true);lyr_Jenengan_Sawit_6.setVisible(true);lyr_Karangduren_Sawit_7.setVisible(true);lyr_Kateguhan_Sawit_8.setVisible(true);lyr_Kemasan_Sawit_9.setVisible(true);lyr_Manjung_Sawit_10.setVisible(true);lyr_Tegalrejo_Sawit_11.setVisible(true);lyr_Tlawong_Sawit_12.setVisible(true);
var layersList = [lyr_OpenStreetMap_0,lyr_Bendosari_Sawit_1,lyr_Cepokosawit_Sawit_2,lyr_Gombang_Sawit_3,lyr_Guwokajen_Sawit_4,lyr_Jatirejo_Sawit_5,lyr_Jenengan_Sawit_6,lyr_Karangduren_Sawit_7,lyr_Kateguhan_Sawit_8,lyr_Kemasan_Sawit_9,lyr_Manjung_Sawit_10,lyr_Tegalrejo_Sawit_11,lyr_Tlawong_Sawit_12];
lyr_Bendosari_Sawit_1.set('fieldAliases', {'BLOK': 'BLOK', 'THN_PAJAK': 'THN_PAJAK', 'NOP': 'NOP', 'NAMA_WP': 'NAMA_WP', 'ALMAT_SUBP': 'ALMAT_SUBP', 'ALMAT_OBJP': 'ALMAT_OBJP', 'KELURAHAN': 'KELURAHAN', 'KECAMATAN': 'KECAMATAN', 'NOMINALPBB': 'NOMINALPBB', 'PBB_DBYR': 'PBB_DBYR', 'SISA_BYR': 'SISA_BYR', 'NIB': 'NIB', 'NHM': 'NHM', 'NO_SU': 'NO_SU', 'LUAS_SERTI': 'LUAS_SERTI', 'LUAS_PETA': 'LUAS_PETA', 'KW': 'KW', 'PMLK_1': 'PMLK_1', 'PMLK_T': 'PMLK_T', 'TIPE_HAK': 'TIPE_HAK', 'NIK': 'NIK', 'PL_CITRA': 'PL_CITRA', 'KLASPL': 'KLASPL', 'SARPRAS': 'SARPRAS', 'RT': 'RT', 'RW': 'RW', 'DUSUN': 'DUSUN', 'KABUPATEN': 'KABUPATEN', 'KETERANGAN': 'KETERANGAN', 'STATUS': 'STATUS', 'RIWAYAT': 'RIWAYAT', 'PETUGAS': 'PETUGAS', 'SERTIPIKAT': 'SERTIPIKAT', 'HARGA': 'HARGA', 'PANEN': 'PANEN', 'IRIGASI': 'IRIGASI', 'PAJAK': 'PAJAK', 'NOC': 'NOC', 'PERSIL': 'PERSIL', 'KELAS': 'KELAS', 'ZNT': 'ZNT', 'KEMISKINAN': 'KEMISKINAN', 'TNH_DESA': 'TNH_DESA', 'TNH_PEMDA': 'TNH_PEMDA', 'KONDISI_JL': 'KONDISI_JL', 'BANTUAN': 'BANTUAN', 'KESEHATAN': 'KESEHATAN', 'LUAS': 'LUAS', 'NOMOR': 'NOMOR', 'NO_KK': 'NO_KK', 'NAMA_KTP': 'NAMA_KTP', 'JNS_KLMN': 'JNS_KLMN', 'TGL_LHR': 'TGL_LHR', 'UMUR': 'UMUR', 'TMP_LHR': 'TMP_LHR', 'ALMT_KTP': 'ALMT_KTP', 'RT_KTP': 'RT_KTP', 'RW_KTP': 'RW_KTP', 'SHDK': 'SHDK', 'STTS_KWN': 'STTS_KWN', 'PENDIDIKAN': 'PENDIDIKAN', 'AGAMA': 'AGAMA', 'PEKERJAAN': 'PEKERJAAN', 'NM_AYAH': 'NM_AYAH', 'NM_IBU': 'NM_IBU', 'D_NOP': 'D_NOP', 'DESA': 'DESA', });
lyr_Cepokosawit_Sawit_2.set('fieldAliases', {'NOP': 'NOP', 'KELURAHAN': 'KELURAHAN', 'KECAMATAN': 'KECAMATAN', 'NIB': 'NIB', 'KW': 'KW', 'NIK': 'NIK', 'PMLK_1': 'PMLK_1', 'PMLK_T': 'PMLK_T', 'PL_CITRA': 'PL_CITRA', 'KLASPL': 'KLASPL', 'SARPRAS': 'SARPRAS', 'D_NOP': 'D_NOP', 'BLOK': 'BLOK', 'THN_PAJAK': 'THN_PAJAK', 'NAMA_WP': 'NAMA_WP', 'ALMAT_SUBP': 'ALMAT_SUBP', 'ALMAT_OBJP': 'ALMAT_OBJP', 'NOMINALPBB': 'NOMINALPBB', 'PBB_DBYR': 'PBB_DBYR', 'SISA_BYR': 'SISA_BYR', 'NHM': 'NHM', 'NO_SU': 'NO_SU', 'LUAS_SERTI': 'LUAS_SERTI', 'LUAS_PETA': 'LUAS_PETA', 'TIPE_HAK': 'TIPE_HAK', 'RT': 'RT', 'RW': 'RW', 'DUSUN': 'DUSUN', 'KABUPATEN': 'KABUPATEN', 'KETERANGAN': 'KETERANGAN', 'STATUS': 'STATUS', 'RIWAYAT': 'RIWAYAT', 'PETUGAS': 'PETUGAS', 'SERTIPIKAT': 'SERTIPIKAT', 'NOMOR': 'NOMOR', 'HARGA': 'HARGA', 'PANEN': 'PANEN', 'IRIGASI': 'IRIGASI', 'PAJAK': 'PAJAK', 'NOC': 'NOC', 'PERSIL': 'PERSIL', 'KELAS': 'KELAS', 'ZNT': 'ZNT', 'KEMISKINAN': 'KEMISKINAN', 'TNH_DESA': 'TNH_DESA', 'TNH_PEMDA': 'TNH_PEMDA', 'BANTUAN': 'BANTUAN', 'KONDISI_JL': 'KONDISI_JL', 'NO_KK': 'NO_KK', 'NAMA_KTP': 'NAMA_KTP', 'JNS_KLMN': 'JNS_KLMN', 'TGL_LHR': 'TGL_LHR', 'UMUR': 'UMUR', 'TMP_LHR': 'TMP_LHR', 'ALMT_KTP': 'ALMT_KTP', 'RT_KTP': 'RT_KTP', 'RW_KTP': 'RW_KTP', 'SHDK': 'SHDK', 'STTS_KWN': 'STTS_KWN', 'PENDIDIKAN': 'PENDIDIKAN', 'AGAMA': 'AGAMA', 'PEKERJAAN': 'PEKERJAAN', 'NM_AYAH': 'NM_AYAH', 'NM_IBU': 'NM_IBU', 'KESEHATAN': 'KESEHATAN', 'LUAS': 'LUAS', 'DESA': 'DESA', });
lyr_Gombang_Sawit_3.set('fieldAliases', {'d_nop': 'd_nop', 'NOP': 'NOP', 'KELURAHAN': 'KELURAHAN', 'KECAMATAN': 'KECAMATAN', 'NIB': 'NIB', 'LUASPETA': 'LUASPETA', 'KW': 'KW', 'THN_PAJAK': 'THN_PAJAK', 'NAMA_WP': 'NAMA_WP', 'ALMAT_SUBP': 'ALMAT_SUBP', 'ALMAT_OBJP': 'ALMAT_OBJP', 'NOMINALPBB': 'NOMINALPBB', 'PBB_DBYR': 'PBB_DBYR', 'SISA_BYR': 'SISA_BYR', 'NHM': 'NHM', 'NO_SU': 'NO_SU', 'LUAS_SERTI': 'LUAS_SERTI', 'PMLK_1': 'PMLK_1', 'PMLK_T': 'PMLK_T', 'TIPE_HAK': 'TIPE_HAK', 'NIK': 'NIK', 'RT': 'RT', 'RW': 'RW', 'DUSUN': 'DUSUN', 'KETERANGAN': 'KETERANGAN', 'STATUS': 'STATUS', 'RIWAYAT': 'RIWAYAT', 'PETUGAS': 'PETUGAS', 'PL_CITRA': 'PL_CITRA', 'NO_KK': 'NO_KK', 'NAMA_KTP': 'NAMA_KTP', 'JNS_KLMN': 'JNS_KLMN', 'TGL_LHR': 'TGL_LHR', 'UMUR': 'UMUR', 'TMP_LHR': 'TMP_LHR', 'ALMT_KTP': 'ALMT_KTP', 'RT_KTP': 'RT_KTP', 'RW_KTP': 'RW_KTP', 'SHDK': 'SHDK', 'STTS_KWN': 'STTS_KWN', 'PENDIDIKAN': 'PENDIDIKAN', 'AGAMA': 'AGAMA', 'PEKERJAAN': 'PEKERJAAN', 'NM_AYAH': 'NM_AYAH', 'NM_IBU': 'NM_IBU', 'DESA': 'DESA', 'KLASPL': 'KLASPL', 'SARPRAS': 'SARPRAS', 'KABUPATEN': 'KABUPATEN', 'SERTIPIKAT': 'SERTIPIKAT', 'HARGA': 'HARGA', 'PANEN': 'PANEN', 'IRIGASI': 'IRIGASI', 'PAJAK': 'PAJAK', 'NOC': 'NOC', 'PERSIL': 'PERSIL', 'KELAS': 'KELAS', 'ZNT': 'ZNT', 'KEMISKINAN': 'KEMISKINAN', 'TNH_DESA': 'TNH_DESA', 'TNH_PEMDA': 'TNH_PEMDA', 'KONDISI_JL': 'KONDISI_JL', 'BANTUAN': 'BANTUAN', 'KESEHATAN': 'KESEHATAN', 'BLOK': 'BLOK', 'NOM': 'NOM', 'NOMOR': 'NOMOR', 'LUAS': 'LUAS', });
lyr_Guwokajen_Sawit_4.set('fieldAliases', {'NO_BIDANG': 'NO_BIDANG', 'NO_BLOK': 'NO_BLOK', 'DNOP': 'DNOP', 'NOP': 'NOP', 'KELURAHAN': 'KELURAHAN', 'KECAMATAN': 'KECAMATAN', 'NIB': 'NIB', 'KW': 'KW', 'PENGGUNAAN': 'PENGGUNAAN', 'NIK': 'NIK', 'KETERANGAN': 'KETERANGAN', 'RIWAYAT': 'RIWAYAT', 'DUSUN': 'DUSUN', 'RT': 'RT', 'RW': 'RW', 'PETUGAS': 'PETUGAS', 'NAMA_KTP': 'NAMA_KTP', 'THN_PAJAK': 'THN_PAJAK', 'NAMA_WP': 'NAMA_WP', 'ALMAT_SUBP': 'ALMAT_SUBP', 'ALMAT_OBJP': 'ALMAT_OBJP', 'NOMINALPBB': 'NOMINALPBB', 'PBB_DBYR': 'PBB_DBYR', 'SISA_BYR': 'SISA_BYR', 'NHM': 'NHM', 'NO_SU': 'NO_SU', 'LUAS_SERTI': 'LUAS_SERTI', 'LUAS_PETA': 'LUAS_PETA', 'PMLK_1': 'PMLK_1', 'PMLK_T': 'PMLK_T', 'TIPE_HAK': 'TIPE_HAK', 'NO_KK': 'NO_KK', 'NAMA_KTP_1': 'NAMA_KTP_1', 'JNS_KLMN': 'JNS_KLMN', 'TGL_LHR': 'TGL_LHR', 'UMUR': 'UMUR', 'TMP_LHR': 'TMP_LHR', 'ALMT_KTP': 'ALMT_KTP', 'RT_KTP': 'RT_KTP', 'RW_KTP': 'RW_KTP', 'SHDK': 'SHDK', 'STTS_KWN': 'STTS_KWN', 'PENDIDIKAN': 'PENDIDIKAN', 'AGAMA': 'AGAMA', 'PEKERJAAN': 'PEKERJAAN', 'NM_AYAH': 'NM_AYAH', 'NM_IBU': 'NM_IBU', 'Shape_Leng': 'Shape_Leng', 'DESA': 'DESA', 'PL_CITRA': 'PL_CITRA', 'KLASPL': 'KLASPL', 'SARPRAS': 'SARPRAS', 'D_NOP': 'D_NOP', 'BLOK': 'BLOK', 'KABUPATEN': 'KABUPATEN', 'STATUS': 'STATUS', 'SERTIPIKAT': 'SERTIPIKAT', 'NOMOR': 'NOMOR', 'HARGA': 'HARGA', 'PANEN': 'PANEN', 'IRIGASI': 'IRIGASI', 'PAJAK': 'PAJAK', 'NOC': 'NOC', 'PERSIL': 'PERSIL', 'KELAS': 'KELAS', 'ZNT': 'ZNT', 'KEMISKINAN': 'KEMISKINAN', 'TNH_DESA': 'TNH_DESA', 'TNH_PEMDA': 'TNH_PEMDA', 'KONDISI_JL': 'KONDISI_JL', 'BANTUAN': 'BANTUAN', 'LUAS': 'LUAS', 'KESEHATAN': 'KESEHATAN', 'NOMOR1': 'NOMOR1', });
lyr_Jatirejo_Sawit_5.set('fieldAliases', {'NOP': 'NOP', 'KELURAHAN': 'KELURAHAN', 'KECAMATAN': 'KECAMATAN', 'WILAYAHID': 'WILAYAHID', 'KODEWILAYA': 'KODEWILAYA', 'NIB': 'NIB', 'KW': 'KW', 'NIK': 'NIK', 'KETERANGAN': 'KETERANGAN', 'RIWAYAT': 'RIWAYAT', 'DUSUN': 'DUSUN', 'RT': 'RT', 'RW': 'RW', 'PETUGAS': 'PETUGAS', 'STATUS': 'STATUS', 'THN_PAJAK': 'THN_PAJAK', 'NAMA_WP': 'NAMA_WP', 'ALMAT_SUBP': 'ALMAT_SUBP', 'ALMAT_OBJP': 'ALMAT_OBJP', 'NOMINALPBB': 'NOMINALPBB', 'PBB_DBYR': 'PBB_DBYR', 'SISA_BYR': 'SISA_BYR', 'NHM': 'NHM', 'NO_SU': 'NO_SU', 'LUAS_SERTI': 'LUAS_SERTI', 'LUAS_PETA': 'LUAS_PETA', 'PMLK_1': 'PMLK_1', 'PMLK_T': 'PMLK_T', 'TIPE_HAK': 'TIPE_HAK', 'NO_KK': 'NO_KK', 'NAMA_KTP': 'NAMA_KTP', 'JNS_KLMN': 'JNS_KLMN', 'TGL_LHR': 'TGL_LHR', 'UMUR': 'UMUR', 'TMP_LHR': 'TMP_LHR', 'ALMT_KTP': 'ALMT_KTP', 'RT_KTP': 'RT_KTP', 'RW_KTP': 'RW_KTP', 'SHDK': 'SHDK', 'STTS_KWN': 'STTS_KWN', 'PENDIDIKAN': 'PENDIDIKAN', 'AGAMA': 'AGAMA', 'PEKERJAAN': 'PEKERJAAN', 'NM_AYAH': 'NM_AYAH', 'NM_IBU': 'NM_IBU', 'PL_CITRA': 'PL_CITRA', 'KLASPL': 'KLASPL', 'SARPRAS': 'SARPRAS', 'SERTIPIKAT': 'SERTIPIKAT', 'HARGA': 'HARGA', 'PANEN': 'PANEN', 'IRIGASI': 'IRIGASI', 'PAJAK': 'PAJAK', 'NOC': 'NOC', 'PERSIL': 'PERSIL', 'KELAS': 'KELAS', 'ZNT': 'ZNT', 'KEMISKINAN': 'KEMISKINAN', 'TNH_DESA': 'TNH_DESA', 'TNH_PEMDA': 'TNH_PEMDA', 'KONDISI_JL': 'KONDISI_JL', 'BANTUAN': 'BANTUAN', 'BLOK': 'BLOK', 'DESA': 'DESA', 'KABUPATEN': 'KABUPATEN', 'NOMOR': 'NOMOR', 'KESEHATAN': 'KESEHATAN', 'DNOP': 'DNOP', 'LUAS': 'LUAS', });
lyr_Jenengan_Sawit_6.set('fieldAliases', {'OBJECTID': 'OBJECTID', 'NOP': 'NOP', 'KELURAHAN': 'KELURAHAN', 'KECAMATAN': 'KECAMATAN', 'NIB': 'NIB', 'NIK': 'NIK', 'KETERANGAN': 'KETERANGAN', 'RIWAYAT': 'RIWAYAT', 'DUSUN': 'DUSUN', 'RT': 'RT', 'RW': 'RW', 'PETUGAS': 'PETUGAS', 'KW': 'KW', 'KLASPL': 'KLASPL', 'SARPRAS': 'SARPRAS', 'KABUPATEN': 'KABUPATEN', 'STATUS': 'STATUS', 'SERTIPIKAT': 'SERTIPIKAT', 'HARGA': 'HARGA', 'PANEN': 'PANEN', 'PAJAK': 'PAJAK', 'TNH_DESA': 'TNH_DESA', 'THN_PAJAK': 'THN_PAJAK', 'NAMA_WP': 'NAMA_WP', 'NOMINALPBB': 'NOMINALPBB', 'PBB_DBYR': 'PBB_DBYR', 'SISA_BYR': 'SISA_BYR', 'NHM': 'NHM', 'NO_SU': 'NO_SU', 'ALMAT_SUBP': 'ALMAT_SUBP', 'ALMAT_OBJP': 'ALMAT_OBJP', 'LUAS_SERTI': 'LUAS_SERTI', 'LUAS_PETA': 'LUAS_PETA', 'PMLK_T': 'PMLK_T', 'TIPE_HAK': 'TIPE_HAK', 'PMLK_1': 'PMLK_1', 'PL_CITRA': 'PL_CITRA', 'IRIGASI': 'IRIGASI', 'NOC': 'NOC', 'PERSIL': 'PERSIL', 'KELAS': 'KELAS', 'ZNT': 'ZNT', 'KEMISKINAN': 'KEMISKINAN', 'TNH_PEMDA': 'TNH_PEMDA', 'KONDISI_JL': 'KONDISI_JL', 'BANTUAN': 'BANTUAN', 'KESEHATAN': 'KESEHATAN', 'NO_': 'NO_', 'NOMOR': 'NOMOR', 'BLOK': 'BLOK', 'D_NOP': 'D_NOP', 'NIK_1': 'NIK_1', 'NO_KK': 'NO_KK', 'NAMA_KTP': 'NAMA_KTP', 'JNS_KLMN': 'JNS_KLMN', 'TGL_LHR': 'TGL_LHR', 'UMUR': 'UMUR', 'TMP_LHR': 'TMP_LHR', 'ALMT_KTP': 'ALMT_KTP', 'RT_KTP': 'RT_KTP', 'RW_KTP': 'RW_KTP', 'KELURAHA_1': 'KELURAHA_1', 'SHDK': 'SHDK', 'STTS_KWN': 'STTS_KWN', 'PENDIDIKAN': 'PENDIDIKAN', 'AGAMA': 'AGAMA', 'PEKERJAAN': 'PEKERJAAN', 'NM_AYAH': 'NM_AYAH', 'NM_IBU': 'NM_IBU', 'LUAS': 'LUAS', 'DESA': 'DESA', });
lyr_Karangduren_Sawit_7.set('fieldAliases', {'OBJECTID': 'OBJECTID', 'NOP': 'NOP', 'KELURAHAN': 'KELURAHAN', 'KECAMATAN': 'KECAMATAN', 'NIB': 'NIB', 'KW': 'KW', 'NIK': 'NIK', 'RT': 'RT', 'RW': 'RW', 'PETUGAS': 'PETUGAS', 'KETERANGAN': 'KETERANGAN', 'RIWAYAT': 'RIWAYAT', 'DUSUN': 'DUSUN', 'STATUS': 'STATUS', 'BANTUAN': 'BANTUAN', 'NAMA_WP': 'NAMA_WP', 'NOMINALPBB': 'NOMINALPBB', 'PBB_DBYR': 'PBB_DBYR', 'SISA_BYR': 'SISA_BYR', 'NHM': 'NHM', 'NO_SU': 'NO_SU', 'LUAS_SERTI': 'LUAS_SERTI', 'LUAS_PETA': 'LUAS_PETA', 'TIPE_HAK': 'TIPE_HAK', 'PL_CITRA': 'PL_CITRA', 'KLASPL': 'KLASPL', 'SARPRAS': 'SARPRAS', 'SERTIPIKAT': 'SERTIPIKAT', 'NOMOR_1': 'NOMOR_1', 'NOMOR': 'NOMOR', 'HARGA': 'HARGA', 'PANEN': 'PANEN', 'IRIGASI': 'IRIGASI', 'PAJAK': 'PAJAK', 'NOC': 'NOC', 'PERSIL': 'PERSIL', 'KELAS': 'KELAS', 'ZNT': 'ZNT', 'KEMISKINAN': 'KEMISKINAN', 'TNH_DESA': 'TNH_DESA', 'TNH_PEMDA': 'TNH_PEMDA', 'KONDISI_JL': 'KONDISI_JL', 'ALMAT_SUBP': 'ALMAT_SUBP', 'ALMAT_OBJP': 'ALMAT_OBJP', 'PMLK_1': 'PMLK_1', 'PMLK_T': 'PMLK_T', 'BLOK': 'BLOK', 'NO_KK': 'NO_KK', 'NAMA_KTP': 'NAMA_KTP', 'JNS_KLMN': 'JNS_KLMN', 'TGL_LHR': 'TGL_LHR', 'UMUR': 'UMUR', 'TMP_LHR': 'TMP_LHR', 'SHDK': 'SHDK', 'STTS_KWN': 'STTS_KWN', 'PENDIDIKAN': 'PENDIDIKAN', 'AGAMA': 'AGAMA', 'PEKERJAAN': 'PEKERJAAN', 'NM_AYAH': 'NM_AYAH', 'NM_IBU': 'NM_IBU', 'KABUPATEN': 'KABUPATEN', 'D_NOP': 'D_NOP', 'Shape_Leng': 'Shape_Leng', 'Shape_Area': 'Shape_Area', 'ALMT_KTP': 'ALMT_KTP', 'RT_KTP': 'RT_KTP', 'RW_KTP': 'RW_KTP', 'DESA': 'DESA', 'THN_PAJAK': 'THN_PAJAK', 'LUAS': 'LUAS', });
lyr_Kateguhan_Sawit_8.set('fieldAliases', {'THN_PAJAK': 'THN_PAJAK', 'NOP': 'NOP', 'NAMA_WP': 'NAMA_WP', 'ALMAT_SUBP': 'ALMAT_SUBP', 'ALMAT_OBJP': 'ALMAT_OBJP', 'KELURAHAN': 'KELURAHAN', 'KECAMATAN': 'KECAMATAN', 'NOMINALPBB': 'NOMINALPBB', 'PBB_DBYR': 'PBB_DBYR', 'SISA_BYR': 'SISA_BYR', 'BLOK': 'BLOK', 'NIB': 'NIB', 'NHM': 'NHM', 'NO_SU': 'NO_SU', 'LUAS_SERTI': 'LUAS_SERTI', 'LUAS_PETA': 'LUAS_PETA', 'KW': 'KW', 'PMLK_1': 'PMLK_1', 'PMLK_T': 'PMLK_T', 'TIPE_HAK': 'TIPE_HAK', 'NIK': 'NIK', 'NO_KK': 'NO_KK', 'NAMA_KTP': 'NAMA_KTP', 'JNS_KLMN': 'JNS_KLMN', 'TGL_LHR': 'TGL_LHR', 'UMUR': 'UMUR', 'TMP_LHR': 'TMP_LHR', 'ALMT_KTP': 'ALMT_KTP', 'RT_KTP': 'RT_KTP', 'RW_KTP': 'RW_KTP', 'SHDK': 'SHDK', 'STTS_KWN': 'STTS_KWN', 'PENDIDIKAN': 'PENDIDIKAN', 'AGAMA': 'AGAMA', 'PEKERJAAN': 'PEKERJAAN', 'NM_AYAH': 'NM_AYAH', 'NM_IBU': 'NM_IBU', 'DESA': 'DESA', 'PL_CITRA': 'PL_CITRA', 'KLASPL': 'KLASPL', 'SARPRAS': 'SARPRAS', 'RT': 'RT', 'RW': 'RW', 'DUSUN': 'DUSUN', 'KABUPATEN': 'KABUPATEN', 'KETERANGAN': 'KETERANGAN', 'STATUS': 'STATUS', 'RIWAYAT': 'RIWAYAT', 'PETUGAS': 'PETUGAS', 'SERTIPIKAT': 'SERTIPIKAT', 'NOMOR': 'NOMOR', 'HARGA': 'HARGA', 'PANEN': 'PANEN', 'IRIGASI': 'IRIGASI', 'PAJAK': 'PAJAK', 'NOC': 'NOC', 'PERSIL': 'PERSIL', 'KELAS': 'KELAS', 'ZNT': 'ZNT', 'KEMISKINAN': 'KEMISKINAN', 'TNH_DESA': 'TNH_DESA', 'TNH_PEMDA': 'TNH_PEMDA', 'KONDISI_JL': 'KONDISI_JL', 'BANTUAN': 'BANTUAN', 'D_NOP': 'D_NOP', 'LUAS': 'LUAS', });
lyr_Kemasan_Sawit_9.set('fieldAliases', {'THN_PAJAK': 'THN_PAJAK', 'NOP': 'NOP', 'NAMA_WP': 'NAMA_WP', 'ALMAT_SUBP': 'ALMAT_SUBP', 'ALMAT_OBJP': 'ALMAT_OBJP', 'KELURAHAN': 'KELURAHAN', 'KECAMATAN': 'KECAMATAN', 'NOMINALPBB': 'NOMINALPBB', 'PBB_DBYR': 'PBB_DBYR', 'SISA_BYR': 'SISA_BYR', 'NHM': 'NHM', 'NO_SU': 'NO_SU', 'NIB': 'NIB', 'LUAS_SERTI': 'LUAS_SERTI', 'LUAS_PETA': 'LUAS_PETA', 'KW': 'KW', 'PMLK_1': 'PMLK_1', 'PMLK_T': 'PMLK_T', 'TIPE_HAK': 'TIPE_HAK', 'NIK': 'NIK', 'NO_KK': 'NO_KK', 'NAMA_KTP': 'NAMA_KTP', 'JNS_KLMN': 'JNS_KLMN', 'TGL_LHR': 'TGL_LHR', 'UMUR': 'UMUR', 'TMP_LHR': 'TMP_LHR', 'ALMT_KTP': 'ALMT_KTP', 'RT_KTP': 'RT_KTP', 'RW_KTP': 'RW_KTP', 'SHDK': 'SHDK', 'STTS_KWN': 'STTS_KWN', 'PENDIDIKAN': 'PENDIDIKAN', 'AGAMA': 'AGAMA', 'PEKERJAAN': 'PEKERJAAN', 'NM_AYAH': 'NM_AYAH', 'NM_IBU': 'NM_IBU', 'PL_CITRA': 'PL_CITRA', 'KLASPL': 'KLASPL', 'SARPRAS': 'SARPRAS', 'D_NOP': 'D_NOP', 'BLOK': 'BLOK', 'RT': 'RT', 'RW': 'RW', 'DUSUN': 'DUSUN', 'KABUPATEN': 'KABUPATEN', 'KETERANGAN': 'KETERANGAN', 'STATUS': 'STATUS', 'RIWAYAT': 'RIWAYAT', 'PETUGAS': 'PETUGAS', 'SERTIPIKAT': 'SERTIPIKAT', 'NOMOR': 'NOMOR', 'HARGA': 'HARGA', 'PANEN': 'PANEN', 'IRIGASI': 'IRIGASI', 'PAJAK': 'PAJAK', 'NOC': 'NOC', 'PERSIL': 'PERSIL', 'KELAS': 'KELAS', 'ZNT': 'ZNT', 'KEMISKINAN': 'KEMISKINAN', 'TNH_DESA': 'TNH_DESA', 'TNH_PEMDA': 'TNH_PEMDA', 'KONDISI_JL': 'KONDISI_JL', 'BANTUAN': 'BANTUAN', 'LUAS': 'LUAS', 'KESEHATAN': 'KESEHATAN', 'DESA': 'DESA', });
lyr_Manjung_Sawit_10.set('fieldAliases', {'THN_PAJAK': 'THN_PAJAK', 'NOP': 'NOP', 'NAMA_WP': 'NAMA_WP', 'ALMAT_SUBP': 'ALMAT_SUBP', 'ALMAT_OBJP': 'ALMAT_OBJP', 'KELURAHAN': 'KELURAHAN', 'KECAMATAN': 'KECAMATAN', 'NOMINALPBB': 'NOMINALPBB', 'PBB_DBYR': 'PBB_DBYR', 'SISA_BYR': 'SISA_BYR', 'NIB': 'NIB', 'NHM': 'NHM', 'NO_SU': 'NO_SU', 'LUAS_SERTI': 'LUAS_SERTI', 'LUAS_PETA': 'LUAS_PETA', 'KW': 'KW', 'PMLK_1': 'PMLK_1', 'PMLK_T': 'PMLK_T', 'TIPE_HAK': 'TIPE_HAK', 'NIK': 'NIK', 'NO_KK': 'NO_KK', 'NAMA_KTP': 'NAMA_KTP', 'JNS_KLMN': 'JNS_KLMN', 'TGL_LHR': 'TGL_LHR', 'UMUR': 'UMUR', 'TMP_LHR': 'TMP_LHR', 'ALMT_KTP': 'ALMT_KTP', 'RT_KTP': 'RT_KTP', 'RW_KTP': 'RW_KTP', 'SHDK': 'SHDK', 'STTS_KWN': 'STTS_KWN', 'PENDIDIKAN': 'PENDIDIKAN', 'AGAMA': 'AGAMA', 'PEKERJAAN': 'PEKERJAAN', 'NM_AYAH': 'NM_AYAH', 'NM_IBU': 'NM_IBU', 'PL_CITRA': 'PL_CITRA', 'KLASPL': 'KLASPL', 'SARPRAS': 'SARPRAS', 'D_NOP': 'D_NOP', 'BLOK': 'BLOK', 'RT': 'RT', 'RW': 'RW', 'DUSUN': 'DUSUN', 'KABUPATEN': 'KABUPATEN', 'KETERANGAN': 'KETERANGAN', 'STATUS': 'STATUS', 'RIWAYAT': 'RIWAYAT', 'PETUGAS': 'PETUGAS', 'SERTIPIKAT': 'SERTIPIKAT', 'NOMOR': 'NOMOR', 'HARGA': 'HARGA', 'PANEN': 'PANEN', 'IRIGASI': 'IRIGASI', 'PAJAK': 'PAJAK', 'NOC': 'NOC', 'PERSIL': 'PERSIL', 'KELAS': 'KELAS', 'ZNT': 'ZNT', 'KEMISKINAN': 'KEMISKINAN', 'TNH_DESA': 'TNH_DESA', 'TNH_PEMDA': 'TNH_PEMDA', 'KONDISI_JL': 'KONDISI_JL', 'BANTUAN': 'BANTUAN', 'KESEHATAN': 'KESEHATAN', 'LUAS': 'LUAS', });
lyr_Tegalrejo_Sawit_11.set('fieldAliases', {'OBJECTID': 'OBJECTID', 'BLOK': 'BLOK', 'NOP': 'NOP', 'KELURAHAN': 'KELURAHAN', 'KECAMATAN': 'KECAMATAN', 'NIB': 'NIB', 'KW': 'KW', 'NIK': 'NIK', 'KETERANGAN': 'KETERANGAN', 'RIWAYAT': 'RIWAYAT', 'DUSUN': 'DUSUN', 'RT': 'RT', 'RW': 'RW', 'PETUGAS': 'PETUGAS', 'NAMA_KTP': 'NAMA_KTP', 'NO_KK': 'NO_KK', 'JNS_KLMN': 'JNS_KLMN', 'TGL_LHR': 'TGL_LHR', 'UMUR': 'UMUR', 'TMP_LHR': 'TMP_LHR', 'ALMT_KTP': 'ALMT_KTP', 'RT_KTP': 'RT_KTP', 'RW_KTP': 'RW_KTP', 'SHDK': 'SHDK', 'STTS_KWN': 'STTS_KWN', 'PENDIDIKAN': 'PENDIDIKAN', 'AGAMA': 'AGAMA', 'PEKERJAAN': 'PEKERJAAN', 'NM_AYAH': 'NM_AYAH', 'NM_IBU': 'NM_IBU', 'THN_PAJAK': 'THN_PAJAK', 'NAMA_WP': 'NAMA_WP', 'NOMINALPBB': 'NOMINALPBB', 'PBB_DBYR': 'PBB_DBYR', 'SISA_BYR': 'SISA_BYR', 'NHM': 'NHM', 'NO_SU': 'NO_SU', 'LUAS_SERTI': 'LUAS_SERTI', 'LUAS_PETA': 'LUAS_PETA', 'PMLK_1': 'PMLK_1', 'PMLK_T': 'PMLK_T', 'TIPE_HAK': 'TIPE_HAK', 'PL_CITRA': 'PL_CITRA', 'KLASPL': 'KLASPL', 'SARPRAS': 'SARPRAS', 'KABUPATEN': 'KABUPATEN', 'STATUS': 'STATUS', 'SERTIPIKAT': 'SERTIPIKAT', 'HARGA': 'HARGA', 'PANEN': 'PANEN', 'IRIGASI': 'IRIGASI', 'PAJAK': 'PAJAK', 'NOC': 'NOC', 'PERSIL': 'PERSIL', 'KELAS': 'KELAS', 'ZNT': 'ZNT', 'KEMISKINAN': 'KEMISKINAN', 'TNH_DESA': 'TNH_DESA', 'TNH_PEMDA': 'TNH_PEMDA', 'KONDISI_JL': 'KONDISI_JL', 'BANTUAN': 'BANTUAN', 'ALMAT_SUBP': 'ALMAT_SUBP', 'ALMAT_OBJP': 'ALMAT_OBJP', 'D_NOP': 'D_NOP', 'Shape_Leng': 'Shape_Leng', 'Shape_Area': 'Shape_Area', 'LUAS': 'LUAS', 'KESEHATAN': 'KESEHATAN', 'NOMOR': 'NOMOR', 'DESA': 'DESA', });
lyr_Tlawong_Sawit_12.set('fieldAliases', {'BLOK': 'BLOK', 'NOP': 'NOP', 'KELURAHAN': 'KELURAHAN', 'KECAMATAN': 'KECAMATAN', 'RT': 'RT', 'RW': 'RW', 'DUSUN': 'DUSUN', 'STATUS': 'STATUS', 'KETERANGAN': 'KETERANGAN', 'PL_CITRA': 'PL_CITRA', 'NIK': 'NIK', 'NHM': 'NHM', 'NO_SU': 'NO_SU', 'NIB': 'NIB', 'LUAS_SERTI': 'LUAS_SERTI', 'LUAS_PETA': 'LUAS_PETA', 'KW': 'KW', 'TIPE_HAK': 'TIPE_HAK', 'PMLK_1': 'PMLK_1', 'PMLK_T': 'PMLK_T', 'RIWAYAT': 'RIWAYAT', 'THN_PAJAK': 'THN_PAJAK', 'NAMA_WP': 'NAMA_WP', 'ALMAT_SUBP': 'ALMAT_SUBP', 'ALMAT_OBJP': 'ALMAT_OBJP', 'NOMINALPBB': 'NOMINALPBB', 'PBB_DBYR': 'PBB_DBYR', 'SISA_BYR': 'SISA_BYR', 'DESA': 'DESA', 'KLASPL': 'KLASPL', 'SARPRAS': 'SARPRAS', 'KABUPATEN': 'KABUPATEN', 'PETUGAS': 'PETUGAS', 'SERTIPIKAT': 'SERTIPIKAT', 'NOMOR': 'NOMOR', 'HARGA': 'HARGA', 'PANEN': 'PANEN', 'IRIGASI': 'IRIGASI', 'PAJAK': 'PAJAK', 'NOC': 'NOC', 'PERSIL': 'PERSIL', 'KELAS': 'KELAS', 'ZNT': 'ZNT', 'KEMISKINAN': 'KEMISKINAN', 'TNH_DESA': 'TNH_DESA', 'TNH_PEMDA': 'TNH_PEMDA', 'KONDISI_JL': 'KONDISI_JL', 'BANTUAN': 'BANTUAN', 'D_NOP': 'D_NOP', 'NO_KK': 'NO_KK', 'NAMA_KTP': 'NAMA_KTP', 'JNS_KLMN': 'JNS_KLMN', 'TGL_LHR': 'TGL_LHR', 'UMUR': 'UMUR', 'TMP_LHR': 'TMP_LHR', 'ALMT_KTP': 'ALMT_KTP', 'RT_KTP': 'RT_KTP', 'RW_KTP': 'RW_KTP', 'SHDK': 'SHDK', 'STTS_KWN': 'STTS_KWN', 'PENDIDIKAN': 'PENDIDIKAN', 'AGAMA': 'AGAMA', 'PEKERJAAN': 'PEKERJAAN', 'NM_AYAH': 'NM_AYAH', 'NM_IBU': 'NM_IBU', 'LUAS': 'LUAS', });
lyr_Bendosari_Sawit_1.set('fieldImages', {'BLOK': '', 'THN_PAJAK': '', 'NOP': '', 'NAMA_WP': '', 'ALMAT_SUBP': '', 'ALMAT_OBJP': '', 'KELURAHAN': '', 'KECAMATAN': '', 'NOMINALPBB': '', 'PBB_DBYR': '', 'SISA_BYR': '', 'NIB': '', 'NHM': '', 'NO_SU': '', 'LUAS_SERTI': '', 'LUAS_PETA': '', 'KW': '', 'PMLK_1': '', 'PMLK_T': '', 'TIPE_HAK': '', 'NIK': '', 'PL_CITRA': '', 'KLASPL': '', 'SARPRAS': '', 'RT': '', 'RW': '', 'DUSUN': '', 'KABUPATEN': '', 'KETERANGAN': '', 'STATUS': '', 'RIWAYAT': '', 'PETUGAS': '', 'SERTIPIKAT': '', 'HARGA': '', 'PANEN': '', 'IRIGASI': '', 'PAJAK': '', 'NOC': '', 'PERSIL': '', 'KELAS': '', 'ZNT': '', 'KEMISKINAN': '', 'TNH_DESA': '', 'TNH_PEMDA': '', 'KONDISI_JL': '', 'BANTUAN': '', 'KESEHATAN': '', 'LUAS': '', 'NOMOR': '', 'NO_KK': '', 'NAMA_KTP': '', 'JNS_KLMN': '', 'TGL_LHR': '', 'UMUR': '', 'TMP_LHR': '', 'ALMT_KTP': '', 'RT_KTP': '', 'RW_KTP': '', 'SHDK': '', 'STTS_KWN': '', 'PENDIDIKAN': '', 'AGAMA': '', 'PEKERJAAN': '', 'NM_AYAH': '', 'NM_IBU': '', 'D_NOP': '', 'DESA': '', });
lyr_Cepokosawit_Sawit_2.set('fieldImages', {'NOP': '', 'KELURAHAN': '', 'KECAMATAN': '', 'NIB': '', 'KW': '', 'NIK': '', 'PMLK_1': '', 'PMLK_T': '', 'PL_CITRA': '', 'KLASPL': '', 'SARPRAS': '', 'D_NOP': '', 'BLOK': '', 'THN_PAJAK': '', 'NAMA_WP': '', 'ALMAT_SUBP': '', 'ALMAT_OBJP': '', 'NOMINALPBB': '', 'PBB_DBYR': '', 'SISA_BYR': '', 'NHM': '', 'NO_SU': '', 'LUAS_SERTI': '', 'LUAS_PETA': '', 'TIPE_HAK': '', 'RT': '', 'RW': '', 'DUSUN': '', 'KABUPATEN': '', 'KETERANGAN': '', 'STATUS': '', 'RIWAYAT': '', 'PETUGAS': '', 'SERTIPIKAT': '', 'NOMOR': '', 'HARGA': '', 'PANEN': '', 'IRIGASI': '', 'PAJAK': '', 'NOC': '', 'PERSIL': '', 'KELAS': '', 'ZNT': '', 'KEMISKINAN': '', 'TNH_DESA': '', 'TNH_PEMDA': '', 'BANTUAN': '', 'KONDISI_JL': '', 'NO_KK': '', 'NAMA_KTP': '', 'JNS_KLMN': '', 'TGL_LHR': '', 'UMUR': '', 'TMP_LHR': '', 'ALMT_KTP': '', 'RT_KTP': '', 'RW_KTP': '', 'SHDK': '', 'STTS_KWN': '', 'PENDIDIKAN': '', 'AGAMA': '', 'PEKERJAAN': '', 'NM_AYAH': '', 'NM_IBU': '', 'KESEHATAN': '', 'LUAS': '', 'DESA': '', });
lyr_Gombang_Sawit_3.set('fieldImages', {'d_nop': '', 'NOP': '', 'KELURAHAN': '', 'KECAMATAN': '', 'NIB': '', 'LUASPETA': '', 'KW': '', 'THN_PAJAK': '', 'NAMA_WP': '', 'ALMAT_SUBP': '', 'ALMAT_OBJP': '', 'NOMINALPBB': '', 'PBB_DBYR': '', 'SISA_BYR': '', 'NHM': '', 'NO_SU': '', 'LUAS_SERTI': '', 'PMLK_1': '', 'PMLK_T': '', 'TIPE_HAK': '', 'NIK': '', 'RT': '', 'RW': '', 'DUSUN': '', 'KETERANGAN': '', 'STATUS': '', 'RIWAYAT': '', 'PETUGAS': '', 'PL_CITRA': '', 'NO_KK': '', 'NAMA_KTP': '', 'JNS_KLMN': '', 'TGL_LHR': '', 'UMUR': '', 'TMP_LHR': '', 'ALMT_KTP': '', 'RT_KTP': '', 'RW_KTP': '', 'SHDK': '', 'STTS_KWN': '', 'PENDIDIKAN': '', 'AGAMA': '', 'PEKERJAAN': '', 'NM_AYAH': '', 'NM_IBU': '', 'DESA': '', 'KLASPL': '', 'SARPRAS': '', 'KABUPATEN': '', 'SERTIPIKAT': '', 'HARGA': '', 'PANEN': '', 'IRIGASI': '', 'PAJAK': '', 'NOC': '', 'PERSIL': '', 'KELAS': '', 'ZNT': '', 'KEMISKINAN': '', 'TNH_DESA': '', 'TNH_PEMDA': '', 'KONDISI_JL': '', 'BANTUAN': '', 'KESEHATAN': '', 'BLOK': '', 'NOM': '', 'NOMOR': '', 'LUAS': '', });
lyr_Guwokajen_Sawit_4.set('fieldImages', {'NO_BIDANG': '', 'NO_BLOK': '', 'DNOP': '', 'NOP': '', 'KELURAHAN': '', 'KECAMATAN': '', 'NIB': '', 'KW': '', 'PENGGUNAAN': '', 'NIK': '', 'KETERANGAN': '', 'RIWAYAT': '', 'DUSUN': '', 'RT': '', 'RW': '', 'PETUGAS': '', 'NAMA_KTP': '', 'THN_PAJAK': '', 'NAMA_WP': '', 'ALMAT_SUBP': '', 'ALMAT_OBJP': '', 'NOMINALPBB': '', 'PBB_DBYR': '', 'SISA_BYR': '', 'NHM': '', 'NO_SU': '', 'LUAS_SERTI': '', 'LUAS_PETA': '', 'PMLK_1': '', 'PMLK_T': '', 'TIPE_HAK': '', 'NO_KK': '', 'NAMA_KTP_1': '', 'JNS_KLMN': '', 'TGL_LHR': '', 'UMUR': '', 'TMP_LHR': '', 'ALMT_KTP': '', 'RT_KTP': '', 'RW_KTP': '', 'SHDK': '', 'STTS_KWN': '', 'PENDIDIKAN': '', 'AGAMA': '', 'PEKERJAAN': '', 'NM_AYAH': '', 'NM_IBU': '', 'Shape_Leng': '', 'DESA': '', 'PL_CITRA': '', 'KLASPL': '', 'SARPRAS': '', 'D_NOP': '', 'BLOK': '', 'KABUPATEN': '', 'STATUS': '', 'SERTIPIKAT': '', 'NOMOR': '', 'HARGA': '', 'PANEN': '', 'IRIGASI': '', 'PAJAK': '', 'NOC': '', 'PERSIL': '', 'KELAS': '', 'ZNT': '', 'KEMISKINAN': '', 'TNH_DESA': '', 'TNH_PEMDA': '', 'KONDISI_JL': '', 'BANTUAN': '', 'LUAS': '', 'KESEHATAN': '', 'NOMOR1': '', });
lyr_Jatirejo_Sawit_5.set('fieldImages', {'NOP': '', 'KELURAHAN': '', 'KECAMATAN': '', 'WILAYAHID': '', 'KODEWILAYA': '', 'NIB': '', 'KW': '', 'NIK': '', 'KETERANGAN': '', 'RIWAYAT': '', 'DUSUN': '', 'RT': '', 'RW': '', 'PETUGAS': '', 'STATUS': '', 'THN_PAJAK': '', 'NAMA_WP': '', 'ALMAT_SUBP': '', 'ALMAT_OBJP': '', 'NOMINALPBB': '', 'PBB_DBYR': '', 'SISA_BYR': '', 'NHM': '', 'NO_SU': '', 'LUAS_SERTI': '', 'LUAS_PETA': '', 'PMLK_1': '', 'PMLK_T': '', 'TIPE_HAK': '', 'NO_KK': '', 'NAMA_KTP': '', 'JNS_KLMN': '', 'TGL_LHR': '', 'UMUR': '', 'TMP_LHR': '', 'ALMT_KTP': '', 'RT_KTP': '', 'RW_KTP': '', 'SHDK': '', 'STTS_KWN': '', 'PENDIDIKAN': '', 'AGAMA': '', 'PEKERJAAN': '', 'NM_AYAH': '', 'NM_IBU': '', 'PL_CITRA': '', 'KLASPL': '', 'SARPRAS': '', 'SERTIPIKAT': '', 'HARGA': '', 'PANEN': '', 'IRIGASI': '', 'PAJAK': '', 'NOC': '', 'PERSIL': '', 'KELAS': '', 'ZNT': '', 'KEMISKINAN': '', 'TNH_DESA': '', 'TNH_PEMDA': '', 'KONDISI_JL': '', 'BANTUAN': '', 'BLOK': '', 'DESA': '', 'KABUPATEN': '', 'NOMOR': '', 'KESEHATAN': '', 'DNOP': '', 'LUAS': '', });
lyr_Jenengan_Sawit_6.set('fieldImages', {'OBJECTID': '', 'NOP': '', 'KELURAHAN': '', 'KECAMATAN': '', 'NIB': '', 'NIK': '', 'KETERANGAN': '', 'RIWAYAT': '', 'DUSUN': '', 'RT': '', 'RW': '', 'PETUGAS': '', 'KW': '', 'KLASPL': '', 'SARPRAS': '', 'KABUPATEN': '', 'STATUS': '', 'SERTIPIKAT': '', 'HARGA': '', 'PANEN': '', 'PAJAK': '', 'TNH_DESA': '', 'THN_PAJAK': '', 'NAMA_WP': '', 'NOMINALPBB': '', 'PBB_DBYR': '', 'SISA_BYR': '', 'NHM': '', 'NO_SU': '', 'ALMAT_SUBP': '', 'ALMAT_OBJP': '', 'LUAS_SERTI': '', 'LUAS_PETA': '', 'PMLK_T': '', 'TIPE_HAK': '', 'PMLK_1': '', 'PL_CITRA': '', 'IRIGASI': '', 'NOC': '', 'PERSIL': '', 'KELAS': '', 'ZNT': '', 'KEMISKINAN': '', 'TNH_PEMDA': '', 'KONDISI_JL': '', 'BANTUAN': '', 'KESEHATAN': '', 'NO_': '', 'NOMOR': '', 'BLOK': '', 'D_NOP': '', 'NIK_1': '', 'NO_KK': '', 'NAMA_KTP': '', 'JNS_KLMN': '', 'TGL_LHR': '', 'UMUR': '', 'TMP_LHR': '', 'ALMT_KTP': '', 'RT_KTP': '', 'RW_KTP': '', 'KELURAHA_1': '', 'SHDK': '', 'STTS_KWN': '', 'PENDIDIKAN': '', 'AGAMA': '', 'PEKERJAAN': '', 'NM_AYAH': '', 'NM_IBU': '', 'LUAS': '', 'DESA': '', });
lyr_Karangduren_Sawit_7.set('fieldImages', {'OBJECTID': '', 'NOP': '', 'KELURAHAN': '', 'KECAMATAN': '', 'NIB': '', 'KW': '', 'NIK': '', 'RT': '', 'RW': '', 'PETUGAS': '', 'KETERANGAN': '', 'RIWAYAT': '', 'DUSUN': '', 'STATUS': '', 'BANTUAN': '', 'NAMA_WP': '', 'NOMINALPBB': '', 'PBB_DBYR': '', 'SISA_BYR': '', 'NHM': '', 'NO_SU': '', 'LUAS_SERTI': '', 'LUAS_PETA': '', 'TIPE_HAK': '', 'PL_CITRA': '', 'KLASPL': '', 'SARPRAS': '', 'SERTIPIKAT': '', 'NOMOR_1': '', 'NOMOR': '', 'HARGA': '', 'PANEN': '', 'IRIGASI': '', 'PAJAK': '', 'NOC': '', 'PERSIL': '', 'KELAS': '', 'ZNT': '', 'KEMISKINAN': '', 'TNH_DESA': '', 'TNH_PEMDA': '', 'KONDISI_JL': '', 'ALMAT_SUBP': '', 'ALMAT_OBJP': '', 'PMLK_1': '', 'PMLK_T': '', 'BLOK': '', 'NO_KK': '', 'NAMA_KTP': '', 'JNS_KLMN': '', 'TGL_LHR': '', 'UMUR': '', 'TMP_LHR': '', 'SHDK': '', 'STTS_KWN': '', 'PENDIDIKAN': '', 'AGAMA': '', 'PEKERJAAN': '', 'NM_AYAH': '', 'NM_IBU': '', 'KABUPATEN': '', 'D_NOP': '', 'Shape_Leng': '', 'Shape_Area': '', 'ALMT_KTP': '', 'RT_KTP': '', 'RW_KTP': '', 'DESA': '', 'THN_PAJAK': '', 'LUAS': '', });
lyr_Kateguhan_Sawit_8.set('fieldImages', {'THN_PAJAK': '', 'NOP': '', 'NAMA_WP': '', 'ALMAT_SUBP': '', 'ALMAT_OBJP': '', 'KELURAHAN': '', 'KECAMATAN': '', 'NOMINALPBB': '', 'PBB_DBYR': '', 'SISA_BYR': '', 'BLOK': '', 'NIB': '', 'NHM': '', 'NO_SU': '', 'LUAS_SERTI': '', 'LUAS_PETA': '', 'KW': '', 'PMLK_1': '', 'PMLK_T': '', 'TIPE_HAK': '', 'NIK': '', 'NO_KK': '', 'NAMA_KTP': '', 'JNS_KLMN': '', 'TGL_LHR': '', 'UMUR': '', 'TMP_LHR': '', 'ALMT_KTP': '', 'RT_KTP': '', 'RW_KTP': '', 'SHDK': '', 'STTS_KWN': '', 'PENDIDIKAN': '', 'AGAMA': '', 'PEKERJAAN': '', 'NM_AYAH': '', 'NM_IBU': '', 'DESA': '', 'PL_CITRA': '', 'KLASPL': '', 'SARPRAS': '', 'RT': '', 'RW': '', 'DUSUN': '', 'KABUPATEN': '', 'KETERANGAN': '', 'STATUS': '', 'RIWAYAT': '', 'PETUGAS': '', 'SERTIPIKAT': '', 'NOMOR': '', 'HARGA': '', 'PANEN': '', 'IRIGASI': '', 'PAJAK': '', 'NOC': '', 'PERSIL': '', 'KELAS': '', 'ZNT': '', 'KEMISKINAN': '', 'TNH_DESA': '', 'TNH_PEMDA': '', 'KONDISI_JL': '', 'BANTUAN': '', 'D_NOP': '', 'LUAS': '', });
lyr_Kemasan_Sawit_9.set('fieldImages', {'THN_PAJAK': '', 'NOP': '', 'NAMA_WP': '', 'ALMAT_SUBP': '', 'ALMAT_OBJP': '', 'KELURAHAN': '', 'KECAMATAN': '', 'NOMINALPBB': '', 'PBB_DBYR': '', 'SISA_BYR': '', 'NHM': '', 'NO_SU': '', 'NIB': '', 'LUAS_SERTI': '', 'LUAS_PETA': '', 'KW': '', 'PMLK_1': '', 'PMLK_T': '', 'TIPE_HAK': '', 'NIK': '', 'NO_KK': '', 'NAMA_KTP': '', 'JNS_KLMN': '', 'TGL_LHR': '', 'UMUR': '', 'TMP_LHR': '', 'ALMT_KTP': '', 'RT_KTP': '', 'RW_KTP': '', 'SHDK': '', 'STTS_KWN': '', 'PENDIDIKAN': '', 'AGAMA': '', 'PEKERJAAN': '', 'NM_AYAH': '', 'NM_IBU': '', 'PL_CITRA': '', 'KLASPL': '', 'SARPRAS': '', 'D_NOP': '', 'BLOK': '', 'RT': '', 'RW': '', 'DUSUN': '', 'KABUPATEN': '', 'KETERANGAN': '', 'STATUS': '', 'RIWAYAT': '', 'PETUGAS': '', 'SERTIPIKAT': '', 'NOMOR': '', 'HARGA': '', 'PANEN': '', 'IRIGASI': '', 'PAJAK': '', 'NOC': '', 'PERSIL': '', 'KELAS': '', 'ZNT': '', 'KEMISKINAN': '', 'TNH_DESA': '', 'TNH_PEMDA': '', 'KONDISI_JL': '', 'BANTUAN': '', 'LUAS': '', 'KESEHATAN': '', 'DESA': '', });
lyr_Manjung_Sawit_10.set('fieldImages', {'THN_PAJAK': '', 'NOP': '', 'NAMA_WP': '', 'ALMAT_SUBP': '', 'ALMAT_OBJP': '', 'KELURAHAN': '', 'KECAMATAN': '', 'NOMINALPBB': '', 'PBB_DBYR': '', 'SISA_BYR': '', 'NIB': '', 'NHM': '', 'NO_SU': '', 'LUAS_SERTI': '', 'LUAS_PETA': '', 'KW': '', 'PMLK_1': '', 'PMLK_T': '', 'TIPE_HAK': '', 'NIK': '', 'NO_KK': '', 'NAMA_KTP': '', 'JNS_KLMN': '', 'TGL_LHR': '', 'UMUR': '', 'TMP_LHR': '', 'ALMT_KTP': '', 'RT_KTP': '', 'RW_KTP': '', 'SHDK': '', 'STTS_KWN': '', 'PENDIDIKAN': '', 'AGAMA': '', 'PEKERJAAN': '', 'NM_AYAH': '', 'NM_IBU': '', 'PL_CITRA': '', 'KLASPL': '', 'SARPRAS': '', 'D_NOP': '', 'BLOK': '', 'RT': '', 'RW': '', 'DUSUN': '', 'KABUPATEN': '', 'KETERANGAN': '', 'STATUS': '', 'RIWAYAT': '', 'PETUGAS': '', 'SERTIPIKAT': '', 'NOMOR': '', 'HARGA': '', 'PANEN': '', 'IRIGASI': '', 'PAJAK': '', 'NOC': '', 'PERSIL': '', 'KELAS': '', 'ZNT': '', 'KEMISKINAN': '', 'TNH_DESA': '', 'TNH_PEMDA': '', 'KONDISI_JL': '', 'BANTUAN': '', 'KESEHATAN': '', 'LUAS': '', });
lyr_Tegalrejo_Sawit_11.set('fieldImages', {'OBJECTID': '', 'BLOK': '', 'NOP': '', 'KELURAHAN': '', 'KECAMATAN': '', 'NIB': '', 'KW': '', 'NIK': '', 'KETERANGAN': '', 'RIWAYAT': '', 'DUSUN': '', 'RT': '', 'RW': '', 'PETUGAS': '', 'NAMA_KTP': '', 'NO_KK': '', 'JNS_KLMN': '', 'TGL_LHR': '', 'UMUR': '', 'TMP_LHR': '', 'ALMT_KTP': '', 'RT_KTP': '', 'RW_KTP': '', 'SHDK': '', 'STTS_KWN': '', 'PENDIDIKAN': '', 'AGAMA': '', 'PEKERJAAN': '', 'NM_AYAH': '', 'NM_IBU': '', 'THN_PAJAK': '', 'NAMA_WP': '', 'NOMINALPBB': '', 'PBB_DBYR': '', 'SISA_BYR': '', 'NHM': '', 'NO_SU': '', 'LUAS_SERTI': '', 'LUAS_PETA': '', 'PMLK_1': '', 'PMLK_T': '', 'TIPE_HAK': '', 'PL_CITRA': '', 'KLASPL': '', 'SARPRAS': '', 'KABUPATEN': '', 'STATUS': '', 'SERTIPIKAT': '', 'HARGA': '', 'PANEN': '', 'IRIGASI': '', 'PAJAK': '', 'NOC': '', 'PERSIL': '', 'KELAS': '', 'ZNT': '', 'KEMISKINAN': '', 'TNH_DESA': '', 'TNH_PEMDA': '', 'KONDISI_JL': '', 'BANTUAN': '', 'ALMAT_SUBP': '', 'ALMAT_OBJP': '', 'D_NOP': '', 'Shape_Leng': '', 'Shape_Area': '', 'LUAS': '', 'KESEHATAN': '', 'NOMOR': '', 'DESA': '', });
lyr_Tlawong_Sawit_12.set('fieldImages', {'BLOK': '', 'NOP': '', 'KELURAHAN': '', 'KECAMATAN': '', 'RT': '', 'RW': '', 'DUSUN': '', 'STATUS': '', 'KETERANGAN': '', 'PL_CITRA': '', 'NIK': '', 'NHM': '', 'NO_SU': '', 'NIB': '', 'LUAS_SERTI': '', 'LUAS_PETA': '', 'KW': '', 'TIPE_HAK': '', 'PMLK_1': '', 'PMLK_T': '', 'RIWAYAT': '', 'THN_PAJAK': '', 'NAMA_WP': '', 'ALMAT_SUBP': '', 'ALMAT_OBJP': '', 'NOMINALPBB': '', 'PBB_DBYR': '', 'SISA_BYR': '', 'DESA': '', 'KLASPL': '', 'SARPRAS': '', 'KABUPATEN': '', 'PETUGAS': '', 'SERTIPIKAT': '', 'NOMOR': '', 'HARGA': '', 'PANEN': '', 'IRIGASI': '', 'PAJAK': '', 'NOC': '', 'PERSIL': '', 'KELAS': '', 'ZNT': '', 'KEMISKINAN': '', 'TNH_DESA': '', 'TNH_PEMDA': '', 'KONDISI_JL': '', 'BANTUAN': '', 'D_NOP': '', 'NO_KK': '', 'NAMA_KTP': '', 'JNS_KLMN': '', 'TGL_LHR': '', 'UMUR': '', 'TMP_LHR': '', 'ALMT_KTP': '', 'RT_KTP': '', 'RW_KTP': '', 'SHDK': '', 'STTS_KWN': '', 'PENDIDIKAN': '', 'AGAMA': '', 'PEKERJAAN': '', 'NM_AYAH': '', 'NM_IBU': '', 'LUAS': '', });
lyr_Bendosari_Sawit_1.set('fieldLabels', {'BLOK': 'no label', 'THN_PAJAK': 'no label', 'NOP': 'no label', 'NAMA_WP': 'no label', 'ALMAT_SUBP': 'no label', 'ALMAT_OBJP': 'no label', 'KELURAHAN': 'no label', 'KECAMATAN': 'no label', 'NOMINALPBB': 'no label', 'PBB_DBYR': 'no label', 'SISA_BYR': 'no label', 'NIB': 'no label', 'NHM': 'no label', 'NO_SU': 'no label', 'LUAS_SERTI': 'no label', 'LUAS_PETA': 'no label', 'KW': 'no label', 'PMLK_1': 'no label', 'PMLK_T': 'no label', 'TIPE_HAK': 'no label', 'NIK': 'no label', 'PL_CITRA': 'no label', 'KLASPL': 'no label', 'SARPRAS': 'no label', 'RT': 'no label', 'RW': 'no label', 'DUSUN': 'no label', 'KABUPATEN': 'no label', 'KETERANGAN': 'no label', 'STATUS': 'no label', 'RIWAYAT': 'no label', 'PETUGAS': 'no label', 'SERTIPIKAT': 'no label', 'HARGA': 'no label', 'PANEN': 'no label', 'IRIGASI': 'no label', 'PAJAK': 'no label', 'NOC': 'no label', 'PERSIL': 'no label', 'KELAS': 'no label', 'ZNT': 'no label', 'KEMISKINAN': 'no label', 'TNH_DESA': 'no label', 'TNH_PEMDA': 'no label', 'KONDISI_JL': 'no label', 'BANTUAN': 'no label', 'KESEHATAN': 'no label', 'LUAS': 'no label', 'NOMOR': 'no label', 'NO_KK': 'no label', 'NAMA_KTP': 'no label', 'JNS_KLMN': 'no label', 'TGL_LHR': 'no label', 'UMUR': 'no label', 'TMP_LHR': 'no label', 'ALMT_KTP': 'no label', 'RT_KTP': 'no label', 'RW_KTP': 'no label', 'SHDK': 'no label', 'STTS_KWN': 'no label', 'PENDIDIKAN': 'no label', 'AGAMA': 'no label', 'PEKERJAAN': 'no label', 'NM_AYAH': 'no label', 'NM_IBU': 'no label', 'D_NOP': 'no label', 'DESA': 'no label', });
lyr_Cepokosawit_Sawit_2.set('fieldLabels', {'NOP': 'no label', 'KELURAHAN': 'no label', 'KECAMATAN': 'no label', 'NIB': 'no label', 'KW': 'no label', 'NIK': 'no label', 'PMLK_1': 'no label', 'PMLK_T': 'no label', 'PL_CITRA': 'no label', 'KLASPL': 'no label', 'SARPRAS': 'no label', 'D_NOP': 'no label', 'BLOK': 'no label', 'THN_PAJAK': 'no label', 'NAMA_WP': 'no label', 'ALMAT_SUBP': 'no label', 'ALMAT_OBJP': 'no label', 'NOMINALPBB': 'no label', 'PBB_DBYR': 'no label', 'SISA_BYR': 'no label', 'NHM': 'no label', 'NO_SU': 'no label', 'LUAS_SERTI': 'no label', 'LUAS_PETA': 'no label', 'TIPE_HAK': 'no label', 'RT': 'no label', 'RW': 'no label', 'DUSUN': 'no label', 'KABUPATEN': 'no label', 'KETERANGAN': 'no label', 'STATUS': 'no label', 'RIWAYAT': 'no label', 'PETUGAS': 'no label', 'SERTIPIKAT': 'no label', 'NOMOR': 'no label', 'HARGA': 'no label', 'PANEN': 'no label', 'IRIGASI': 'no label', 'PAJAK': 'no label', 'NOC': 'no label', 'PERSIL': 'no label', 'KELAS': 'no label', 'ZNT': 'no label', 'KEMISKINAN': 'no label', 'TNH_DESA': 'no label', 'TNH_PEMDA': 'no label', 'BANTUAN': 'no label', 'KONDISI_JL': 'no label', 'NO_KK': 'no label', 'NAMA_KTP': 'no label', 'JNS_KLMN': 'no label', 'TGL_LHR': 'no label', 'UMUR': 'no label', 'TMP_LHR': 'no label', 'ALMT_KTP': 'no label', 'RT_KTP': 'no label', 'RW_KTP': 'no label', 'SHDK': 'no label', 'STTS_KWN': 'no label', 'PENDIDIKAN': 'no label', 'AGAMA': 'no label', 'PEKERJAAN': 'no label', 'NM_AYAH': 'no label', 'NM_IBU': 'no label', 'KESEHATAN': 'no label', 'LUAS': 'no label', 'DESA': 'no label', });
lyr_Gombang_Sawit_3.set('fieldLabels', {'d_nop': 'no label', 'NOP': 'no label', 'KELURAHAN': 'no label', 'KECAMATAN': 'no label', 'NIB': 'no label', 'LUASPETA': 'no label', 'KW': 'no label', 'THN_PAJAK': 'no label', 'NAMA_WP': 'no label', 'ALMAT_SUBP': 'no label', 'ALMAT_OBJP': 'no label', 'NOMINALPBB': 'no label', 'PBB_DBYR': 'no label', 'SISA_BYR': 'no label', 'NHM': 'no label', 'NO_SU': 'no label', 'LUAS_SERTI': 'no label', 'PMLK_1': 'no label', 'PMLK_T': 'no label', 'TIPE_HAK': 'no label', 'NIK': 'no label', 'RT': 'no label', 'RW': 'no label', 'DUSUN': 'no label', 'KETERANGAN': 'no label', 'STATUS': 'no label', 'RIWAYAT': 'no label', 'PETUGAS': 'no label', 'PL_CITRA': 'no label', 'NO_KK': 'no label', 'NAMA_KTP': 'no label', 'JNS_KLMN': 'no label', 'TGL_LHR': 'no label', 'UMUR': 'no label', 'TMP_LHR': 'no label', 'ALMT_KTP': 'no label', 'RT_KTP': 'no label', 'RW_KTP': 'no label', 'SHDK': 'no label', 'STTS_KWN': 'no label', 'PENDIDIKAN': 'no label', 'AGAMA': 'no label', 'PEKERJAAN': 'no label', 'NM_AYAH': 'no label', 'NM_IBU': 'no label', 'DESA': 'no label', 'KLASPL': 'no label', 'SARPRAS': 'no label', 'KABUPATEN': 'no label', 'SERTIPIKAT': 'no label', 'HARGA': 'no label', 'PANEN': 'no label', 'IRIGASI': 'no label', 'PAJAK': 'no label', 'NOC': 'no label', 'PERSIL': 'no label', 'KELAS': 'no label', 'ZNT': 'no label', 'KEMISKINAN': 'no label', 'TNH_DESA': 'no label', 'TNH_PEMDA': 'no label', 'KONDISI_JL': 'no label', 'BANTUAN': 'no label', 'KESEHATAN': 'no label', 'BLOK': 'no label', 'NOM': 'no label', 'NOMOR': 'no label', 'LUAS': 'no label', });
lyr_Guwokajen_Sawit_4.set('fieldLabels', {'NO_BIDANG': 'no label', 'NO_BLOK': 'no label', 'DNOP': 'no label', 'NOP': 'no label', 'KELURAHAN': 'no label', 'KECAMATAN': 'no label', 'NIB': 'no label', 'KW': 'no label', 'PENGGUNAAN': 'no label', 'NIK': 'no label', 'KETERANGAN': 'no label', 'RIWAYAT': 'no label', 'DUSUN': 'no label', 'RT': 'no label', 'RW': 'no label', 'PETUGAS': 'no label', 'NAMA_KTP': 'no label', 'THN_PAJAK': 'no label', 'NAMA_WP': 'no label', 'ALMAT_SUBP': 'no label', 'ALMAT_OBJP': 'no label', 'NOMINALPBB': 'no label', 'PBB_DBYR': 'no label', 'SISA_BYR': 'no label', 'NHM': 'no label', 'NO_SU': 'no label', 'LUAS_SERTI': 'no label', 'LUAS_PETA': 'no label', 'PMLK_1': 'no label', 'PMLK_T': 'no label', 'TIPE_HAK': 'no label', 'NO_KK': 'no label', 'NAMA_KTP_1': 'no label', 'JNS_KLMN': 'no label', 'TGL_LHR': 'no label', 'UMUR': 'no label', 'TMP_LHR': 'no label', 'ALMT_KTP': 'no label', 'RT_KTP': 'no label', 'RW_KTP': 'no label', 'SHDK': 'no label', 'STTS_KWN': 'no label', 'PENDIDIKAN': 'no label', 'AGAMA': 'no label', 'PEKERJAAN': 'no label', 'NM_AYAH': 'no label', 'NM_IBU': 'no label', 'Shape_Leng': 'no label', 'DESA': 'no label', 'PL_CITRA': 'no label', 'KLASPL': 'no label', 'SARPRAS': 'no label', 'D_NOP': 'no label', 'BLOK': 'no label', 'KABUPATEN': 'no label', 'STATUS': 'no label', 'SERTIPIKAT': 'no label', 'NOMOR': 'no label', 'HARGA': 'no label', 'PANEN': 'no label', 'IRIGASI': 'no label', 'PAJAK': 'no label', 'NOC': 'no label', 'PERSIL': 'no label', 'KELAS': 'no label', 'ZNT': 'no label', 'KEMISKINAN': 'no label', 'TNH_DESA': 'no label', 'TNH_PEMDA': 'no label', 'KONDISI_JL': 'no label', 'BANTUAN': 'no label', 'LUAS': 'no label', 'KESEHATAN': 'no label', 'NOMOR1': 'no label', });
lyr_Jatirejo_Sawit_5.set('fieldLabels', {'NOP': 'no label', 'KELURAHAN': 'no label', 'KECAMATAN': 'no label', 'WILAYAHID': 'no label', 'KODEWILAYA': 'no label', 'NIB': 'no label', 'KW': 'no label', 'NIK': 'no label', 'KETERANGAN': 'no label', 'RIWAYAT': 'no label', 'DUSUN': 'no label', 'RT': 'no label', 'RW': 'no label', 'PETUGAS': 'no label', 'STATUS': 'no label', 'THN_PAJAK': 'no label', 'NAMA_WP': 'no label', 'ALMAT_SUBP': 'no label', 'ALMAT_OBJP': 'no label', 'NOMINALPBB': 'no label', 'PBB_DBYR': 'no label', 'SISA_BYR': 'no label', 'NHM': 'no label', 'NO_SU': 'no label', 'LUAS_SERTI': 'no label', 'LUAS_PETA': 'no label', 'PMLK_1': 'no label', 'PMLK_T': 'no label', 'TIPE_HAK': 'no label', 'NO_KK': 'no label', 'NAMA_KTP': 'no label', 'JNS_KLMN': 'no label', 'TGL_LHR': 'no label', 'UMUR': 'no label', 'TMP_LHR': 'no label', 'ALMT_KTP': 'no label', 'RT_KTP': 'no label', 'RW_KTP': 'no label', 'SHDK': 'no label', 'STTS_KWN': 'no label', 'PENDIDIKAN': 'no label', 'AGAMA': 'no label', 'PEKERJAAN': 'no label', 'NM_AYAH': 'no label', 'NM_IBU': 'no label', 'PL_CITRA': 'no label', 'KLASPL': 'no label', 'SARPRAS': 'no label', 'SERTIPIKAT': 'no label', 'HARGA': 'no label', 'PANEN': 'no label', 'IRIGASI': 'no label', 'PAJAK': 'no label', 'NOC': 'no label', 'PERSIL': 'no label', 'KELAS': 'no label', 'ZNT': 'no label', 'KEMISKINAN': 'no label', 'TNH_DESA': 'no label', 'TNH_PEMDA': 'no label', 'KONDISI_JL': 'no label', 'BANTUAN': 'no label', 'BLOK': 'no label', 'DESA': 'no label', 'KABUPATEN': 'no label', 'NOMOR': 'no label', 'KESEHATAN': 'no label', 'DNOP': 'no label', 'LUAS': 'no label', });
lyr_Jenengan_Sawit_6.set('fieldLabels', {'OBJECTID': 'no label', 'NOP': 'no label', 'KELURAHAN': 'no label', 'KECAMATAN': 'no label', 'NIB': 'no label', 'NIK': 'no label', 'KETERANGAN': 'no label', 'RIWAYAT': 'no label', 'DUSUN': 'no label', 'RT': 'no label', 'RW': 'no label', 'PETUGAS': 'no label', 'KW': 'no label', 'KLASPL': 'no label', 'SARPRAS': 'no label', 'KABUPATEN': 'no label', 'STATUS': 'no label', 'SERTIPIKAT': 'no label', 'HARGA': 'no label', 'PANEN': 'no label', 'PAJAK': 'no label', 'TNH_DESA': 'no label', 'THN_PAJAK': 'no label', 'NAMA_WP': 'no label', 'NOMINALPBB': 'no label', 'PBB_DBYR': 'no label', 'SISA_BYR': 'no label', 'NHM': 'no label', 'NO_SU': 'no label', 'ALMAT_SUBP': 'no label', 'ALMAT_OBJP': 'no label', 'LUAS_SERTI': 'no label', 'LUAS_PETA': 'no label', 'PMLK_T': 'no label', 'TIPE_HAK': 'no label', 'PMLK_1': 'no label', 'PL_CITRA': 'no label', 'IRIGASI': 'no label', 'NOC': 'no label', 'PERSIL': 'no label', 'KELAS': 'no label', 'ZNT': 'no label', 'KEMISKINAN': 'no label', 'TNH_PEMDA': 'no label', 'KONDISI_JL': 'no label', 'BANTUAN': 'no label', 'KESEHATAN': 'no label', 'NO_': 'no label', 'NOMOR': 'no label', 'BLOK': 'no label', 'D_NOP': 'no label', 'NIK_1': 'no label', 'NO_KK': 'no label', 'NAMA_KTP': 'no label', 'JNS_KLMN': 'no label', 'TGL_LHR': 'no label', 'UMUR': 'no label', 'TMP_LHR': 'no label', 'ALMT_KTP': 'no label', 'RT_KTP': 'no label', 'RW_KTP': 'no label', 'KELURAHA_1': 'no label', 'SHDK': 'no label', 'STTS_KWN': 'no label', 'PENDIDIKAN': 'no label', 'AGAMA': 'no label', 'PEKERJAAN': 'no label', 'NM_AYAH': 'no label', 'NM_IBU': 'no label', 'LUAS': 'no label', 'DESA': 'no label', });
lyr_Karangduren_Sawit_7.set('fieldLabels', {'OBJECTID': 'no label', 'NOP': 'no label', 'KELURAHAN': 'no label', 'KECAMATAN': 'no label', 'NIB': 'no label', 'KW': 'no label', 'NIK': 'no label', 'RT': 'no label', 'RW': 'no label', 'PETUGAS': 'no label', 'KETERANGAN': 'no label', 'RIWAYAT': 'no label', 'DUSUN': 'no label', 'STATUS': 'no label', 'BANTUAN': 'no label', 'NAMA_WP': 'no label', 'NOMINALPBB': 'no label', 'PBB_DBYR': 'no label', 'SISA_BYR': 'no label', 'NHM': 'no label', 'NO_SU': 'no label', 'LUAS_SERTI': 'no label', 'LUAS_PETA': 'no label', 'TIPE_HAK': 'no label', 'PL_CITRA': 'no label', 'KLASPL': 'no label', 'SARPRAS': 'no label', 'SERTIPIKAT': 'no label', 'NOMOR_1': 'no label', 'NOMOR': 'no label', 'HARGA': 'no label', 'PANEN': 'no label', 'IRIGASI': 'no label', 'PAJAK': 'no label', 'NOC': 'no label', 'PERSIL': 'no label', 'KELAS': 'no label', 'ZNT': 'no label', 'KEMISKINAN': 'no label', 'TNH_DESA': 'no label', 'TNH_PEMDA': 'no label', 'KONDISI_JL': 'no label', 'ALMAT_SUBP': 'no label', 'ALMAT_OBJP': 'no label', 'PMLK_1': 'no label', 'PMLK_T': 'no label', 'BLOK': 'no label', 'NO_KK': 'no label', 'NAMA_KTP': 'no label', 'JNS_KLMN': 'no label', 'TGL_LHR': 'no label', 'UMUR': 'no label', 'TMP_LHR': 'no label', 'SHDK': 'no label', 'STTS_KWN': 'no label', 'PENDIDIKAN': 'no label', 'AGAMA': 'no label', 'PEKERJAAN': 'no label', 'NM_AYAH': 'no label', 'NM_IBU': 'no label', 'KABUPATEN': 'no label', 'D_NOP': 'no label', 'Shape_Leng': 'no label', 'Shape_Area': 'no label', 'ALMT_KTP': 'no label', 'RT_KTP': 'no label', 'RW_KTP': 'no label', 'DESA': 'no label', 'THN_PAJAK': 'no label', 'LUAS': 'no label', });
lyr_Kateguhan_Sawit_8.set('fieldLabels', {'THN_PAJAK': 'no label', 'NOP': 'no label', 'NAMA_WP': 'no label', 'ALMAT_SUBP': 'no label', 'ALMAT_OBJP': 'no label', 'KELURAHAN': 'no label', 'KECAMATAN': 'no label', 'NOMINALPBB': 'no label', 'PBB_DBYR': 'no label', 'SISA_BYR': 'no label', 'BLOK': 'no label', 'NIB': 'no label', 'NHM': 'no label', 'NO_SU': 'no label', 'LUAS_SERTI': 'no label', 'LUAS_PETA': 'no label', 'KW': 'no label', 'PMLK_1': 'no label', 'PMLK_T': 'no label', 'TIPE_HAK': 'no label', 'NIK': 'no label', 'NO_KK': 'no label', 'NAMA_KTP': 'no label', 'JNS_KLMN': 'no label', 'TGL_LHR': 'no label', 'UMUR': 'no label', 'TMP_LHR': 'no label', 'ALMT_KTP': 'no label', 'RT_KTP': 'no label', 'RW_KTP': 'no label', 'SHDK': 'no label', 'STTS_KWN': 'no label', 'PENDIDIKAN': 'no label', 'AGAMA': 'no label', 'PEKERJAAN': 'no label', 'NM_AYAH': 'no label', 'NM_IBU': 'no label', 'DESA': 'no label', 'PL_CITRA': 'no label', 'KLASPL': 'no label', 'SARPRAS': 'no label', 'RT': 'no label', 'RW': 'no label', 'DUSUN': 'no label', 'KABUPATEN': 'no label', 'KETERANGAN': 'no label', 'STATUS': 'no label', 'RIWAYAT': 'no label', 'PETUGAS': 'no label', 'SERTIPIKAT': 'no label', 'NOMOR': 'no label', 'HARGA': 'no label', 'PANEN': 'no label', 'IRIGASI': 'no label', 'PAJAK': 'no label', 'NOC': 'no label', 'PERSIL': 'no label', 'KELAS': 'no label', 'ZNT': 'no label', 'KEMISKINAN': 'no label', 'TNH_DESA': 'no label', 'TNH_PEMDA': 'no label', 'KONDISI_JL': 'no label', 'BANTUAN': 'no label', 'D_NOP': 'no label', 'LUAS': 'no label', });
lyr_Kemasan_Sawit_9.set('fieldLabels', {'THN_PAJAK': 'no label', 'NOP': 'no label', 'NAMA_WP': 'no label', 'ALMAT_SUBP': 'no label', 'ALMAT_OBJP': 'no label', 'KELURAHAN': 'no label', 'KECAMATAN': 'no label', 'NOMINALPBB': 'no label', 'PBB_DBYR': 'no label', 'SISA_BYR': 'no label', 'NHM': 'no label', 'NO_SU': 'no label', 'NIB': 'no label', 'LUAS_SERTI': 'no label', 'LUAS_PETA': 'no label', 'KW': 'no label', 'PMLK_1': 'no label', 'PMLK_T': 'no label', 'TIPE_HAK': 'no label', 'NIK': 'no label', 'NO_KK': 'no label', 'NAMA_KTP': 'no label', 'JNS_KLMN': 'no label', 'TGL_LHR': 'no label', 'UMUR': 'no label', 'TMP_LHR': 'no label', 'ALMT_KTP': 'no label', 'RT_KTP': 'no label', 'RW_KTP': 'no label', 'SHDK': 'no label', 'STTS_KWN': 'no label', 'PENDIDIKAN': 'no label', 'AGAMA': 'no label', 'PEKERJAAN': 'no label', 'NM_AYAH': 'no label', 'NM_IBU': 'no label', 'PL_CITRA': 'no label', 'KLASPL': 'no label', 'SARPRAS': 'no label', 'D_NOP': 'no label', 'BLOK': 'no label', 'RT': 'no label', 'RW': 'no label', 'DUSUN': 'no label', 'KABUPATEN': 'no label', 'KETERANGAN': 'no label', 'STATUS': 'no label', 'RIWAYAT': 'no label', 'PETUGAS': 'no label', 'SERTIPIKAT': 'no label', 'NOMOR': 'no label', 'HARGA': 'no label', 'PANEN': 'no label', 'IRIGASI': 'no label', 'PAJAK': 'no label', 'NOC': 'no label', 'PERSIL': 'no label', 'KELAS': 'no label', 'ZNT': 'no label', 'KEMISKINAN': 'no label', 'TNH_DESA': 'no label', 'TNH_PEMDA': 'no label', 'KONDISI_JL': 'no label', 'BANTUAN': 'no label', 'LUAS': 'no label', 'KESEHATAN': 'no label', 'DESA': 'no label', });
lyr_Manjung_Sawit_10.set('fieldLabels', {'THN_PAJAK': 'no label', 'NOP': 'no label', 'NAMA_WP': 'no label', 'ALMAT_SUBP': 'no label', 'ALMAT_OBJP': 'no label', 'KELURAHAN': 'no label', 'KECAMATAN': 'no label', 'NOMINALPBB': 'no label', 'PBB_DBYR': 'no label', 'SISA_BYR': 'no label', 'NIB': 'no label', 'NHM': 'no label', 'NO_SU': 'no label', 'LUAS_SERTI': 'no label', 'LUAS_PETA': 'no label', 'KW': 'no label', 'PMLK_1': 'no label', 'PMLK_T': 'no label', 'TIPE_HAK': 'no label', 'NIK': 'no label', 'NO_KK': 'no label', 'NAMA_KTP': 'no label', 'JNS_KLMN': 'no label', 'TGL_LHR': 'no label', 'UMUR': 'no label', 'TMP_LHR': 'no label', 'ALMT_KTP': 'no label', 'RT_KTP': 'no label', 'RW_KTP': 'no label', 'SHDK': 'no label', 'STTS_KWN': 'no label', 'PENDIDIKAN': 'no label', 'AGAMA': 'no label', 'PEKERJAAN': 'no label', 'NM_AYAH': 'no label', 'NM_IBU': 'no label', 'PL_CITRA': 'no label', 'KLASPL': 'no label', 'SARPRAS': 'no label', 'D_NOP': 'no label', 'BLOK': 'no label', 'RT': 'no label', 'RW': 'no label', 'DUSUN': 'no label', 'KABUPATEN': 'no label', 'KETERANGAN': 'no label', 'STATUS': 'no label', 'RIWAYAT': 'no label', 'PETUGAS': 'no label', 'SERTIPIKAT': 'no label', 'NOMOR': 'no label', 'HARGA': 'no label', 'PANEN': 'no label', 'IRIGASI': 'no label', 'PAJAK': 'no label', 'NOC': 'no label', 'PERSIL': 'no label', 'KELAS': 'no label', 'ZNT': 'no label', 'KEMISKINAN': 'no label', 'TNH_DESA': 'no label', 'TNH_PEMDA': 'no label', 'KONDISI_JL': 'no label', 'BANTUAN': 'no label', 'KESEHATAN': 'no label', 'LUAS': 'no label', });
lyr_Tegalrejo_Sawit_11.set('fieldLabels', {'OBJECTID': 'no label', 'BLOK': 'no label', 'NOP': 'no label', 'KELURAHAN': 'no label', 'KECAMATAN': 'no label', 'NIB': 'no label', 'KW': 'no label', 'NIK': 'no label', 'KETERANGAN': 'no label', 'RIWAYAT': 'no label', 'DUSUN': 'no label', 'RT': 'no label', 'RW': 'no label', 'PETUGAS': 'no label', 'NAMA_KTP': 'no label', 'NO_KK': 'no label', 'JNS_KLMN': 'no label', 'TGL_LHR': 'no label', 'UMUR': 'no label', 'TMP_LHR': 'no label', 'ALMT_KTP': 'no label', 'RT_KTP': 'no label', 'RW_KTP': 'no label', 'SHDK': 'no label', 'STTS_KWN': 'no label', 'PENDIDIKAN': 'no label', 'AGAMA': 'no label', 'PEKERJAAN': 'no label', 'NM_AYAH': 'no label', 'NM_IBU': 'no label', 'THN_PAJAK': 'no label', 'NAMA_WP': 'no label', 'NOMINALPBB': 'no label', 'PBB_DBYR': 'no label', 'SISA_BYR': 'no label', 'NHM': 'no label', 'NO_SU': 'no label', 'LUAS_SERTI': 'no label', 'LUAS_PETA': 'no label', 'PMLK_1': 'no label', 'PMLK_T': 'no label', 'TIPE_HAK': 'no label', 'PL_CITRA': 'no label', 'KLASPL': 'no label', 'SARPRAS': 'no label', 'KABUPATEN': 'no label', 'STATUS': 'no label', 'SERTIPIKAT': 'no label', 'HARGA': 'no label', 'PANEN': 'no label', 'IRIGASI': 'no label', 'PAJAK': 'no label', 'NOC': 'no label', 'PERSIL': 'no label', 'KELAS': 'no label', 'ZNT': 'no label', 'KEMISKINAN': 'no label', 'TNH_DESA': 'no label', 'TNH_PEMDA': 'no label', 'KONDISI_JL': 'no label', 'BANTUAN': 'no label', 'ALMAT_SUBP': 'no label', 'ALMAT_OBJP': 'no label', 'D_NOP': 'no label', 'Shape_Leng': 'no label', 'Shape_Area': 'no label', 'LUAS': 'no label', 'KESEHATAN': 'no label', 'NOMOR': 'no label', 'DESA': 'no label', });
lyr_Tlawong_Sawit_12.set('fieldLabels', {'BLOK': 'no label', 'NOP': 'no label', 'KELURAHAN': 'no label', 'KECAMATAN': 'no label', 'RT': 'no label', 'RW': 'no label', 'DUSUN': 'no label', 'STATUS': 'no label', 'KETERANGAN': 'no label', 'PL_CITRA': 'no label', 'NIK': 'no label', 'NHM': 'no label', 'NO_SU': 'no label', 'NIB': 'no label', 'LUAS_SERTI': 'no label', 'LUAS_PETA': 'no label', 'KW': 'no label', 'TIPE_HAK': 'no label', 'PMLK_1': 'no label', 'PMLK_T': 'no label', 'RIWAYAT': 'no label', 'THN_PAJAK': 'no label', 'NAMA_WP': 'no label', 'ALMAT_SUBP': 'no label', 'ALMAT_OBJP': 'no label', 'NOMINALPBB': 'no label', 'PBB_DBYR': 'no label', 'SISA_BYR': 'no label', 'DESA': 'no label', 'KLASPL': 'no label', 'SARPRAS': 'no label', 'KABUPATEN': 'no label', 'PETUGAS': 'no label', 'SERTIPIKAT': 'no label', 'NOMOR': 'no label', 'HARGA': 'no label', 'PANEN': 'no label', 'IRIGASI': 'no label', 'PAJAK': 'no label', 'NOC': 'no label', 'PERSIL': 'no label', 'KELAS': 'no label', 'ZNT': 'no label', 'KEMISKINAN': 'no label', 'TNH_DESA': 'no label', 'TNH_PEMDA': 'no label', 'KONDISI_JL': 'no label', 'BANTUAN': 'no label', 'D_NOP': 'no label', 'NO_KK': 'no label', 'NAMA_KTP': 'no label', 'JNS_KLMN': 'no label', 'TGL_LHR': 'no label', 'UMUR': 'no label', 'TMP_LHR': 'no label', 'ALMT_KTP': 'no label', 'RT_KTP': 'no label', 'RW_KTP': 'no label', 'SHDK': 'no label', 'STTS_KWN': 'no label', 'PENDIDIKAN': 'no label', 'AGAMA': 'no label', 'PEKERJAAN': 'no label', 'NM_AYAH': 'no label', 'NM_IBU': 'no label', 'LUAS': 'no label', });
lyr_Tlawong_Sawit_12.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});